# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      nuget-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
      nuget-majors:
        patterns: ["*"]
        update-types: ["major"]
      nuget-security:
        applies-to: security-updates
        patterns: ["*"]

# dotnet updates: https://devblogs.microsoft.com/dotnet/using-dependabot-to-manage-dotnet-sdk-updates/