//HintName: GeneratedDispatcher.g.cs
// <auto-generated/>
#nullable enable
using System.Text.Json;

using Underground.Outbox.Data;
using Underground.Outbox.Domain.Dispatchers;
using Underground.Outbox.Exceptions;
using Microsoft.Extensions.DependencyInjection;

namespace Underground.Outbox.Domain;

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
public class GeneratedDispatcher<TMessage> : IMessageDispatcher<TMessage> where TMessage : class, IMessage
{
    public async Task ExecuteAsync(IServiceScope scope, TMessage message, CancellationToken cancellationToken)
    {
        var metadata = new MessageMetadata(message.EventId, message.PartitionKey, message.RetryCount);
        var serviceProvider = scope.ServiceProvider;
        if (typeof(TMessage) == typeof(InboxMessage))
        {
            switch (message.Type)
            {
                default:
                    throw new ParsingException($"No handler configured for message type {message.Type} of message: {message.Id}");
            }
        }

        if (typeof(TMessage) == typeof(OutboxMessage))
        {
            switch (message.Type)
            {
                default:
                    throw new ParsingException($"No handler configured for message type {message.Type} of message: {message.Id}");
            }
        }

        throw new ParsingException($"Unsupported dispatcher message type {typeof(TMessage).FullName}");
    }
}
#pragma warning restore CS1591
