//HintName: OutboxDependencyInjection.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

using Microsoft.Extensions.DependencyInjection;

using Underground.Outbox.Data;
using Underground.Outbox.Domain;
using Underground.Outbox.Domain.Dispatchers;

namespace Underground.Outbox.Configuration;

/// <summary>Registers the inbox and outbox of each DbContext this compilation declares handlers for.</summary>
public static class ConfigureOutboxServices
{
    /// <summary>Registers the Sample.BillingContext outbox. Set <c>Schema</c> to the schema its <c>outbox</c> table lives in.</summary>
    public static IServiceCollection AddBillingContextOutboxServices(
        this IServiceCollection services,
        Action<OutboxServiceConfiguration<global::Sample.BillingContext>> configuration)
    {
        services.AddScoped<IMessageDispatcher<global::Sample.BillingContext, OutboxMessage>, Dispatcher_Sample_BillingContext<OutboxMessage>>();
        SetupServices.SetupInternalOutboxServices<global::Sample.BillingContext>(services, configuration);

        return services;
    }

    /// <summary>Registers the Sample.OrdersContext outbox. Set <c>Schema</c> to the schema its <c>outbox</c> table lives in.</summary>
    public static IServiceCollection AddOrdersContextOutboxServices(
        this IServiceCollection services,
        Action<OutboxServiceConfiguration<global::Sample.OrdersContext>> configuration)
    {
        services.AddScoped<IMessageDispatcher<global::Sample.OrdersContext, OutboxMessage>, Dispatcher_Sample_OrdersContext<OutboxMessage>>();
        SetupServices.SetupInternalOutboxServices<global::Sample.OrdersContext>(services, configuration);

        return services;
    }
}
#pragma warning restore CS1591
