//HintName: OutboxHandlerRegistration.g.cs
// <auto-generated/>
#nullable enable

using System;
using System.Text.Json;

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

using Underground.Outbox.Data;
using Underground.Outbox.Domain.Dispatchers;
using Underground.Outbox.Exceptions;

namespace Underground.Outbox.Configuration;

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
public static class GeneratorTestsHandlerRegistration
{
    /// <summary>Registers the message handlers declared in the GeneratorTests assembly.</summary>
    public static IServiceCollection AddGeneratorTestsMessageHandlers(this IServiceCollection services)
    {
        services.TryAddScoped<global::Sample.BothHandler>();
        services.TryAddScoped<global::Underground.Outbox.IOutboxMessageHandler<global::Sample.First>>(static serviceProvider => serviceProvider.GetRequiredService<global::Sample.BothHandler>());
        services.TryAddScoped<global::Underground.Outbox.IOutboxMessageHandler<global::Sample.Second>>(static serviceProvider => serviceProvider.GetRequiredService<global::Sample.BothHandler>());

        services.AddSingleton(new HandlerEntry<OutboxMessage>(
            typeof(global::Sample.First).FullName!,
            typeof(global::Sample.BothHandler),
            typeof(global::Sample.First),
            static async (serviceProvider, message, metadata, cancellationToken) =>
            {
                var payload = JsonSerializer.Deserialize<global::Sample.First>(message.Data)
                    ?? throw new ParsingException($"Cannot parse event body of message: {message.Id}");
                var handler = serviceProvider.GetRequiredService<global::Underground.Outbox.IOutboxMessageHandler<global::Sample.First>>();
                try
                {
                    await handler.HandleAsync(payload, metadata, cancellationToken);
                }
                catch (Exception ex) when (ex is not OperationCanceledException || !cancellationToken.IsCancellationRequested)
                {
                    throw new MessageHandlerException(
                        handler.GetType(),
                        typeof(global::Sample.First),
                        $"Error processing message {message.Id} with handler {handler.GetType().Name}",
                        ex
                    );
                }
            }));

        services.AddSingleton(new HandlerEntry<OutboxMessage>(
            typeof(global::Sample.Second).FullName!,
            typeof(global::Sample.BothHandler),
            typeof(global::Sample.Second),
            static async (serviceProvider, message, metadata, cancellationToken) =>
            {
                var payload = JsonSerializer.Deserialize<global::Sample.Second>(message.Data)
                    ?? throw new ParsingException($"Cannot parse event body of message: {message.Id}");
                var handler = serviceProvider.GetRequiredService<global::Underground.Outbox.IOutboxMessageHandler<global::Sample.Second>>();
                try
                {
                    await handler.HandleAsync(payload, metadata, cancellationToken);
                }
                catch (Exception ex) when (ex is not OperationCanceledException || !cancellationToken.IsCancellationRequested)
                {
                    throw new MessageHandlerException(
                        handler.GetType(),
                        typeof(global::Sample.Second),
                        $"Error processing message {message.Id} with handler {handler.GetType().Name}",
                        ex
                    );
                }
            }));

        return services;
    }
}
#pragma warning restore CS1591
