//HintName: OutboxDependencyInjection.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

using Microsoft.Extensions.DependencyInjection;

using Underground.Outbox.Data;
using Underground.Outbox.Domain;
using Underground.Outbox.Domain.Dispatchers;

namespace Underground.Outbox.Configuration;

/// <summary>Registers the inbox and outbox of each DbContext this compilation declares handlers for.</summary>
public static class ConfigureOutboxServices
{
    /// <summary>Registers the Orders.AppDbContext outbox. Set <c>Schema</c> to the schema its <c>outbox</c> table lives in.</summary>
    public static IServiceCollection AddOrders_AppDbContextOutboxServices(
        this IServiceCollection services,
        Action<OutboxServiceConfiguration<global::Orders.AppDbContext>> configuration)
    {
        services.AddScoped<IMessageDispatcher<global::Orders.AppDbContext, OutboxMessage>, Dispatcher_Orders_AppDbContext<OutboxMessage>>();
        SetupServices.SetupInternalOutboxServices<global::Orders.AppDbContext>(services, configuration);

        return services;
    }

    /// <summary>Registers the Orders.Billing.AppDbContext outbox. Set <c>Schema</c> to the schema its <c>outbox</c> table lives in.</summary>
    public static IServiceCollection AddOrders_Billing_AppDbContextOutboxServices(
        this IServiceCollection services,
        Action<OutboxServiceConfiguration<global::Orders.Billing.AppDbContext>> configuration)
    {
        services.AddScoped<IMessageDispatcher<global::Orders.Billing.AppDbContext, OutboxMessage>, Dispatcher_Orders_Billing_AppDbContext<OutboxMessage>>();
        SetupServices.SetupInternalOutboxServices<global::Orders.Billing.AppDbContext>(services, configuration);

        return services;
    }
}
#pragma warning restore CS1591
