//HintName: OutboxDependencyInjection.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

using Microsoft.Extensions.DependencyInjection;

using Underground.Outbox.Data;
using Underground.Outbox.Domain;
using Underground.Outbox.Domain.Dispatchers;

namespace Underground.Outbox.Configuration;

/// <summary>Registers the inbox and outbox of each DbContext this compilation declares handlers for.</summary>
public static class ConfigureOutboxServices
{
}
#pragma warning restore CS1591
