//HintName: OutboxHandlerRegistration.g.cs
// <auto-generated/>
#nullable enable

using System;
using System.Text.Json;

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

using Underground.Outbox.Data;
using Underground.Outbox.Domain.Dispatchers;
using Underground.Outbox.Exceptions;

namespace Underground.Outbox.Configuration;

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
public static class GeneratorTestsHandlerRegistration
{
    /// <summary>Registers the message handlers declared in the GeneratorTests assembly.</summary>
    public static IServiceCollection AddGeneratorTestsMessageHandlers(this IServiceCollection services)
    {
        services.TryAddTransient<global::Sample.InnerHandler>();
        services.TryAddTransient<global::Underground.Outbox.IOutboxMessageHandler<global::Sample.Outer.Inner>>(static serviceProvider => serviceProvider.GetRequiredService<global::Sample.InnerHandler>());

        services.AddSingleton(new HandlerEntry<OutboxMessage>(
            typeof(global::Sample.Outer.Inner).FullName!,
            typeof(global::Sample.InnerHandler),
            typeof(global::Sample.Outer.Inner),
            static async (serviceProvider, message, metadata, cancellationToken) =>
            {
                var payload = JsonSerializer.Deserialize<global::Sample.Outer.Inner>(message.Data)
                    ?? throw new ParsingException($"Cannot parse event body {message.Data} of message: {message.Id}");
                var handler = serviceProvider.GetRequiredService<global::Underground.Outbox.IOutboxMessageHandler<global::Sample.Outer.Inner>>();
                try
                {
                    await handler.HandleAsync(payload, metadata, cancellationToken);
                }
                catch (Exception ex) when (ex is not OperationCanceledException)
                {
                    throw new MessageHandlerException(
                        handler.GetType(),
                        typeof(global::Sample.Outer.Inner),
                        $"Error processing message {message.Id} with handler {handler.GetType().Name}",
                        ex
                    );
                }
            }));

        return services;
    }
}
#pragma warning restore CS1591
