//HintName: OutboxHandlerRegistration.g.cs
// <auto-generated/>
#nullable enable

using System;
using System.Text.Json;

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

using Underground.Outbox.Data;
using Underground.Outbox.Domain.Dispatchers;
using Underground.Outbox.Exceptions;

namespace Underground.Outbox.Configuration;

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
public static class GeneratorTestsHandlerRegistration
{
    /// <summary>Registers the message handlers declared in the GeneratorTests assembly.</summary>
    public static IServiceCollection AddGeneratorTestsMessageHandlers(this IServiceCollection services)
    {
        services.TryAddScoped<global::Sample.BothHandler>();
        services.TryAddScoped<global::Underground.Outbox.IOutboxMessageHandler<global::Sample.First>>(static serviceProvider => serviceProvider.GetRequiredService<global::Sample.BothHandler>());
        services.TryAddScoped<global::Underground.Outbox.IOutboxMessageHandler<global::Sample.Second>>(static serviceProvider => serviceProvider.GetRequiredService<global::Sample.BothHandler>());

        services.AddSingleton(new HandlerEntry<OutboxMessage>(
            typeof(global::Sample.First).FullName!,
            typeof(global::Sample.BothHandler),
            typeof(global::Sample.First),
            static async (serviceProvider, message, metadata, cancellationToken) =>
            {
                var payload = JsonSerializer.Deserialize<global::Sample.First>(message.Data)
                    ?? throw new JsonException($"The payload of message {message.Id} is the JSON literal null.");
                global::Underground.Outbox.IOutboxMessageHandler<global::Sample.First> handler;
                try
                {
                    handler = serviceProvider.GetRequiredService<global::Underground.Outbox.IOutboxMessageHandler<global::Sample.First>>();
                }
                catch (Exception ex)
                {
                    throw new HandlerResolutionException(typeof(global::Sample.BothHandler), message.Id, ex);
                }
                await handler.HandleAsync(payload, metadata, cancellationToken);
            }));

        services.AddSingleton(new HandlerEntry<OutboxMessage>(
            typeof(global::Sample.Second).FullName!,
            typeof(global::Sample.BothHandler),
            typeof(global::Sample.Second),
            static async (serviceProvider, message, metadata, cancellationToken) =>
            {
                var payload = JsonSerializer.Deserialize<global::Sample.Second>(message.Data)
                    ?? throw new JsonException($"The payload of message {message.Id} is the JSON literal null.");
                global::Underground.Outbox.IOutboxMessageHandler<global::Sample.Second> handler;
                try
                {
                    handler = serviceProvider.GetRequiredService<global::Underground.Outbox.IOutboxMessageHandler<global::Sample.Second>>();
                }
                catch (Exception ex)
                {
                    throw new HandlerResolutionException(typeof(global::Sample.BothHandler), message.Id, ex);
                }
                await handler.HandleAsync(payload, metadata, cancellationToken);
            }));

        return services;
    }
}
#pragma warning restore CS1591
