//HintName: OutboxHandlerRegistration.g.cs
// <auto-generated/>
#nullable enable

using System;
using System.Text.Json;

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

using Underground.Outbox.Data;
using Underground.Outbox.Domain.Dispatchers;
using Underground.Outbox.Exceptions;

namespace Underground.Outbox.Configuration;

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
public static class GeneratorTestsHandlerRegistration
{
    /// <summary>Registers the message handlers declared in the GeneratorTests assembly.</summary>
    public static IServiceCollection AddGeneratorTestsMessageHandlers(this IServiceCollection services)
    {
        services.TryAddTransient<global::Sample.InboxHandler>();
        services.TryAddTransient<global::Underground.Outbox.IInboxMessageHandler<global::Sample.InboxMessageType>>(static serviceProvider => serviceProvider.GetRequiredService<global::Sample.InboxHandler>());
        services.TryAddTransient<global::Sample.OutboxHandler>();
        services.TryAddTransient<global::Underground.Outbox.IOutboxMessageHandler<global::Sample.OutboxMessageType>>(static serviceProvider => serviceProvider.GetRequiredService<global::Sample.OutboxHandler>());

        services.AddSingleton(new HandlerEntry<InboxMessage>(
            typeof(global::Sample.InboxMessageType).FullName!,
            typeof(global::Sample.InboxHandler),
            typeof(global::Sample.InboxMessageType),
            static async (serviceProvider, message, metadata, cancellationToken) =>
            {
                var payload = JsonSerializer.Deserialize<global::Sample.InboxMessageType>(message.Data)
                    ?? throw new ParsingException($"Cannot parse event body of message: {message.Id}");
                var handler = serviceProvider.GetRequiredService<global::Underground.Outbox.IInboxMessageHandler<global::Sample.InboxMessageType>>();
                try
                {
                    await handler.HandleAsync(payload, metadata, cancellationToken);
                }
                catch (Exception ex) when (ex is not OperationCanceledException || !cancellationToken.IsCancellationRequested)
                {
                    throw new MessageHandlerException(
                        handler.GetType(),
                        typeof(global::Sample.InboxMessageType),
                        $"Error processing message {message.Id} with handler {handler.GetType().Name}",
                        ex
                    );
                }
            }));

        services.AddSingleton(new HandlerEntry<OutboxMessage>(
            typeof(global::Sample.OutboxMessageType).FullName!,
            typeof(global::Sample.OutboxHandler),
            typeof(global::Sample.OutboxMessageType),
            static async (serviceProvider, message, metadata, cancellationToken) =>
            {
                var payload = JsonSerializer.Deserialize<global::Sample.OutboxMessageType>(message.Data)
                    ?? throw new ParsingException($"Cannot parse event body of message: {message.Id}");
                var handler = serviceProvider.GetRequiredService<global::Underground.Outbox.IOutboxMessageHandler<global::Sample.OutboxMessageType>>();
                try
                {
                    await handler.HandleAsync(payload, metadata, cancellationToken);
                }
                catch (Exception ex) when (ex is not OperationCanceledException || !cancellationToken.IsCancellationRequested)
                {
                    throw new MessageHandlerException(
                        handler.GetType(),
                        typeof(global::Sample.OutboxMessageType),
                        $"Error processing message {message.Id} with handler {handler.GetType().Name}",
                        ex
                    );
                }
            }));

        return services;
    }
}
#pragma warning restore CS1591
