//HintName: OutboxHandlerRegistration.g.cs
// <auto-generated/>
#nullable enable

using System;
using System.Text.Json;

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

using Underground.Outbox.Data;
using Underground.Outbox.Domain.Dispatchers;
using Underground.Outbox.Exceptions;

namespace Underground.Outbox.Configuration;

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
public static class GeneratorTestsHandlerRegistration
{
    /// <summary>Registers the message handlers declared in the GeneratorTests assembly.</summary>
    public static IServiceCollection AddGeneratorTestsMessageHandlers(this IServiceCollection services)
    {
        services.TryAddTransient<global::Sample.EnvelopeHandler>();
        services.TryAddTransient<global::Underground.Outbox.IOutboxMessageHandler<global::Sample.Envelope<global::Sample.Payload>>>(static serviceProvider => serviceProvider.GetRequiredService<global::Sample.EnvelopeHandler>());

        services.AddSingleton(new HandlerEntry<OutboxMessage>(
            typeof(global::Sample.Envelope<global::Sample.Payload>).FullName!,
            typeof(global::Sample.EnvelopeHandler),
            typeof(global::Sample.Envelope<global::Sample.Payload>),
            static async (serviceProvider, message, metadata, cancellationToken) =>
            {
                var payload = JsonSerializer.Deserialize<global::Sample.Envelope<global::Sample.Payload>>(message.Data)
                    ?? throw new JsonException($"The payload of message {message.Id} is the JSON literal null.");
                global::Underground.Outbox.IOutboxMessageHandler<global::Sample.Envelope<global::Sample.Payload>> handler;
                try
                {
                    handler = serviceProvider.GetRequiredService<global::Underground.Outbox.IOutboxMessageHandler<global::Sample.Envelope<global::Sample.Payload>>>();
                }
                catch (Exception ex)
                {
                    throw new HandlerResolutionException(typeof(global::Sample.EnvelopeHandler), message.Id, ex);
                }
                await handler.HandleAsync(payload, metadata, cancellationToken);
            }));

        return services;
    }
}
#pragma warning restore CS1591
