//HintName: GeneratedDispatcher.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

using System;
using System.Text.Json;

using Underground.Outbox.Data;
using Underground.Outbox.Domain.Dispatchers;
using Underground.Outbox.Exceptions;
using Microsoft.Extensions.DependencyInjection;

namespace Underground.Outbox.Domain;
#pragma warning restore CS1591
