//HintName: OutboxHandlerRegistration.g.cs
// <auto-generated/>
#nullable enable

using System;
using System.Text.Json;

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

using Underground.Outbox.Data;
using Underground.Outbox.Domain.Dispatchers;
using Underground.Outbox.Exceptions;

namespace Underground.Outbox.Configuration;

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
public static class GeneratorTestsHandlerRegistration
{
    /// <summary>Registers the message handlers declared in the GeneratorTests assembly.</summary>
    public static IServiceCollection AddGeneratorTestsMessageHandlers(this IServiceCollection services)
    {
        services.TryAddTransient<global::Sample.FirstHandler>();
        services.TryAddTransient<global::Underground.Outbox.IOutboxMessageHandler<global::Sample.TestMessage>>(static serviceProvider => serviceProvider.GetRequiredService<global::Sample.FirstHandler>());
        services.TryAddTransient<global::Sample.SecondHandler>();
        services.TryAddTransient<global::Underground.Outbox.IOutboxMessageHandler<global::Sample.TestMessage>>(static serviceProvider => serviceProvider.GetRequiredService<global::Sample.SecondHandler>());

        services.AddSingleton(new HandlerEntry<OutboxMessage>(
            typeof(global::Sample.TestMessage).FullName!,
            typeof(global::Sample.FirstHandler),
            typeof(global::Sample.TestMessage),
            static async (serviceProvider, message, metadata, cancellationToken) =>
            {
                var payload = JsonSerializer.Deserialize<global::Sample.TestMessage>(message.Data)
                    ?? throw new ParsingException($"Cannot parse event body {message.Data} of message: {message.Id}");
                var handler = serviceProvider.GetRequiredService<global::Underground.Outbox.IOutboxMessageHandler<global::Sample.TestMessage>>();
                try
                {
                    await handler.HandleAsync(payload, metadata, cancellationToken);
                }
                catch (Exception ex) when (ex is not OperationCanceledException)
                {
                    throw new MessageHandlerException(
                        handler.GetType(),
                        typeof(global::Sample.TestMessage),
                        $"Error processing message {message.Id} with handler {handler.GetType().Name}",
                        ex
                    );
                }
            }));

        services.AddSingleton(new HandlerEntry<OutboxMessage>(
            typeof(global::Sample.TestMessage).FullName!,
            typeof(global::Sample.SecondHandler),
            typeof(global::Sample.TestMessage),
            static async (serviceProvider, message, metadata, cancellationToken) =>
            {
                var payload = JsonSerializer.Deserialize<global::Sample.TestMessage>(message.Data)
                    ?? throw new ParsingException($"Cannot parse event body {message.Data} of message: {message.Id}");
                var handler = serviceProvider.GetRequiredService<global::Underground.Outbox.IOutboxMessageHandler<global::Sample.TestMessage>>();
                try
                {
                    await handler.HandleAsync(payload, metadata, cancellationToken);
                }
                catch (Exception ex) when (ex is not OperationCanceledException)
                {
                    throw new MessageHandlerException(
                        handler.GetType(),
                        typeof(global::Sample.TestMessage),
                        $"Error processing message {message.Id} with handler {handler.GetType().Name}",
                        ex
                    );
                }
            }));

        return services;
    }
}
#pragma warning restore CS1591
