//HintName: GeneratedDispatcher.g.cs
// <auto-generated/>
#nullable enable
using System.Text.Json;

using Underground.Outbox.Data;
using Underground.Outbox.Domain.Dispatchers;
using Underground.Outbox.Exceptions;
using Microsoft.Extensions.DependencyInjection;

namespace Underground.Outbox.Domain;

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
public class GeneratedDispatcher<TMessage> : IMessageDispatcher<TMessage> where TMessage : class, IMessage
{
    public async Task ExecuteAsync(IServiceScope scope, TMessage message, CancellationToken cancellationToken)
    {
        var metadata = new MessageMetadata(message.EventId, message.PartitionKey, message.RetryCount);
        var serviceProvider = scope.ServiceProvider;
        if (typeof(TMessage) == typeof(InboxMessage))
        {
            switch (message.Type)
            {
                case "Sample.InboxMessageType":
                {
                    var fullEvent = JsonSerializer.Deserialize<Sample.InboxMessageType>(message.Data) ?? throw new ParsingException($"Cannot parse event body {message.Data} of message: {message.Id}");
                    var handler = serviceProvider.GetRequiredService<IInboxMessageHandler<Sample.InboxMessageType>>();
                    try
                    {
                        await handler.HandleAsync(fullEvent, metadata, cancellationToken);
                        return;
                    }
                    catch (Exception ex) when (ex is not OperationCanceledException)
                    {
                        throw new MessageHandlerException(
                            handler.GetType(),
                            typeof(Sample.InboxMessageType),
                            $"Error processing message {message.Id} with handler {handler.GetType().Name}",
                            ex
                        );
                    }
                }
                default:
                    throw new ParsingException($"No handler configured for message type {message.Type} of message: {message.Id}");
            }
        }

        if (typeof(TMessage) == typeof(OutboxMessage))
        {
            switch (message.Type)
            {
                case "Sample.OutboxMessageType":
                {
                    var fullEvent = JsonSerializer.Deserialize<Sample.OutboxMessageType>(message.Data) ?? throw new ParsingException($"Cannot parse event body {message.Data} of message: {message.Id}");
                    var handler = serviceProvider.GetRequiredService<IOutboxMessageHandler<Sample.OutboxMessageType>>();
                    try
                    {
                        await handler.HandleAsync(fullEvent, metadata, cancellationToken);
                        return;
                    }
                    catch (Exception ex) when (ex is not OperationCanceledException)
                    {
                        throw new MessageHandlerException(
                            handler.GetType(),
                            typeof(Sample.OutboxMessageType),
                            $"Error processing message {message.Id} with handler {handler.GetType().Name}",
                            ex
                        );
                    }
                }
                default:
                    throw new ParsingException($"No handler configured for message type {message.Type} of message: {message.Id}");
            }
        }

        throw new ParsingException($"Unsupported dispatcher message type {typeof(TMessage).FullName}");
    }
}
#pragma warning restore CS1591
