//HintName: GeneratedDispatcher.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

using System;
using System.Text.Json;

using Underground.Outbox.Data;
using Underground.Outbox.Domain.Dispatchers;
using Underground.Outbox.Exceptions;
using Microsoft.Extensions.DependencyInjection;

namespace Underground.Outbox.Domain;

/// <summary>Dispatches the messages of the Sample.OrdersContext inbox and outbox to the handlers bound to it.</summary>
internal sealed class Dispatcher_Sample_OrdersContext<TMessage> : IMessageDispatcher<global::Sample.OrdersContext, TMessage> where TMessage : class, IMessage
{
    public async Task ExecuteAsync(IServiceScope scope, TMessage message, CancellationToken cancellationToken)
    {
        var metadata = new MessageMetadata(message.EventId, message.GroupKey, message.RetryCount);
        var serviceProvider = scope.ServiceProvider;
        if (typeof(TMessage) == typeof(InboxMessage))
        {
            throw new ParsingException($"No handler configured for message type {message.Type} of message: {message.Id}");
        }

        if (typeof(TMessage) == typeof(OutboxMessage))
        {
            if (string.Equals(message.Type, typeof(global::Sample.Outer.Inner).FullName, StringComparison.Ordinal))
            {
                var fullEvent = JsonSerializer.Deserialize<global::Sample.Outer.Inner>(message.Data) ?? throw new ParsingException($"Cannot parse event body {message.Data} of message: {message.Id}");
                var handler = serviceProvider.GetRequiredKeyedService<IOutboxMessageHandler<global::Sample.Outer.Inner>>(typeof(global::Sample.OrdersContext));
                try
                {
                    await handler.HandleAsync(fullEvent, metadata, cancellationToken);
                    return;
                }
                catch (Exception ex) when (ex is not OperationCanceledException)
                {
                    throw new MessageHandlerException(
                        handler.GetType(),
                        typeof(global::Sample.Outer.Inner),
                        $"Error processing message {message.Id} with handler {handler.GetType().Name}",
                        ex
                    );
                }
            }

            throw new ParsingException($"No handler configured for message type {message.Type} of message: {message.Id}");
        }

        throw new ParsingException($"Unsupported dispatcher message type {typeof(TMessage).FullName}");
    }
}
#pragma warning restore CS1591
