using System.Collections.Immutable;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Underground.Outbox.SourceGenerator;

[Generator]
public sealed class OutboxGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (s, _) => IsSyntaxTargetForGeneration(s),
                static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null);

        var collectedHandlers = classDeclarations.Collect();

        context.RegisterSourceOutput(
            collectedHandlers,
            static (spc, source) => Execute(source, spc));
    }

    private static bool IsSyntaxTargetForGeneration(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax { BaseList.Types.Count: > 0 };
    }

    private static HandlerClassInfo? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;

        foreach (var baseType in classDeclaration.BaseList!.Types)
        {
            var typeInfo = context.SemanticModel.GetTypeInfo(baseType.Type);
            if (typeInfo.Type is INamedTypeSymbol typeSymbol
            && typeSymbol.IsGenericType
            // && typeSymbol.OriginalDefinition.ToDisplayString().Contains("IOutboxMessageHandler"))
            && typeSymbol.OriginalDefinition.ToDisplayString() == "Underground.Outbox.IOutboxMessageHandler<T>")
            {
                return new HandlerClassInfo(
                    typeSymbol.ContainingNamespace.ToDisplayString(),
                    // classDeclaration.Identifier.Text,
                    typeSymbol.OriginalDefinition.ToDisplayString(),
                    typeSymbol.TypeArguments[0].ToDisplayString()
                );
            }
        }

        return null;
    }

    private static void Execute(ImmutableArray<HandlerClassInfo?> classes, SourceProductionContext context)
    {
        var handlers = classes.Where(c => c is not null).ToList();

        // if (handlers.Count == 0)
        // {
        //     return;
        // }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        // sb.AppendLine("using System;");
        sb.AppendLine("using Underground.Outbox.Data;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace Underground.Outbox.Domain;");
        sb.AppendLine();
        sb.AppendLine("public static class OutboxHandlers<TMessage> where TMessage : class, IMessage");
        sb.AppendLine("{");
        sb.AppendLine("    public static async Task CallHandlerAsync(TMessage message, IServiceScope scope, CancellationToken cancellationToken)");
        sb.AppendLine("    {");

        sb.AppendLine($"// {handlers.Count}");

        foreach (var classInfo in handlers)
        {
            sb.AppendLine($"        if (message.Type == \"{classInfo?.ClassName}\")");
            sb.AppendLine("        {");
            sb.AppendLine("        }");
            sb.AppendLine();
            //     var model = compilation.GetSemanticModel(classDecl.SyntaxTree);
            //     var classSymbol = model.GetDeclaredSymbol(classDecl);

            //     if (classSymbol is not null)
            //     {
            //         var fullName = classSymbol.ToDisplayString();
            //         sb.AppendLine($"            typeof({fullName}),");
            //     }
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("OutboxHandlers.g.cs", sb.ToString());
    }

    // https://andrewlock.net/creating-a-source-generator-part-5-finding-a-type-declarations-namespace-and-type-hierarchy/
    // static string GetNamespace(BaseTypeDeclarationSyntax syntax)
    // {
    //     string nameSpace = string.Empty;

    //     // Get the containing syntax node for the type declaration
    //     // (could be a nested type, for example)
    //     SyntaxNode? potentialNamespaceParent = syntax.Parent;

    //     // Keep moving "out" of nested classes etc until we get to a namespace
    //     // or until we run out of parents
    //     while (potentialNamespaceParent != null &&
    //             potentialNamespaceParent is not NamespaceDeclarationSyntax
    //             && potentialNamespaceParent is not FileScopedNamespaceDeclarationSyntax)
    //     {
    //         potentialNamespaceParent = potentialNamespaceParent.Parent;
    //     }

    //     // Build up the final namespace by looping until we no longer have a namespace declaration
    //     if (potentialNamespaceParent is BaseNamespaceDeclarationSyntax namespaceParent)
    //     {
    //         // We have a namespace. Use that as the type
    //         nameSpace = namespaceParent.Name.ToString();

    //         // Keep moving "out" of the namespace declarations until we
    //         // run out of nested namespace declarations
    //         while (true)
    //         {
    //             if (namespaceParent.Parent is not NamespaceDeclarationSyntax parent)
    //             {
    //                 break;
    //             }

    //             // Add the outer namespace as a prefix to the final namespace
    //             nameSpace = $"{namespaceParent.Name}.{nameSpace}";
    //             namespaceParent = parent;
    //         }
    //     }

    //     // return the final namespace
    //     return nameSpace;
    // }

}
