using Microsoft.CodeAnalysis;

namespace Underground.Outbox.SourceGenerator;

[Generator]
public sealed class OutboxGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, static (spc, _) =>
        {
            spc.AddSource("Hello.g.cs",
                """
                // <auto-generated/>
                #nullable enable

                namespace Underground.Outbox.Domain;
                public static class Hello
                {
                    public static string Message => "Hello from an incremental generator!!!";
                }
                """);
        });
    }
}
