name: Release to nuget.org

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    # https://learn.microsoft.com/en-us/nuget/nuget-org/trusted-publishing
    # https://devblogs.microsoft.com/dotnet/enhanced-security-is-here-with-the-new-trust-publishing-on-nuget-org/
    permissions:
      id-token: write  # enable GitHub OIDC token issuance for this job

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Build
      run: dotnet build --configuration Release
    - name: Pack
      run: dotnet pack src/Underground.Outbox/Underground.Outbox.csproj
    # Get a short-lived NuGet API key
    - name: NuGet login (OIDC → temp API key)
      uses: NuGet/login@v1
      id: login
      with:
        # Recommended: use a secret like ${{ secrets.NUGET_USER }} for your nuget.org username (profile name), NOT your email address
        user: ${{ secrets.NUGET_USER }}
    - name: Publish
      run: dotnet nuget push "src/Underground.Outbox/bin/Release/Underground.Outbox.*.nupkg" --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
